name = "jflib"
version = "VERSION"
license = "MIT"
author = "Laszlo Szathmary"
maintainer = "jabba.laci@gmail.com"
copyright = "Copyright 2026, Laszlo Szathmary alias Jabba Laci"

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[preprocess]
[preprocess.cpp]
suffixes = [".F90", ".f90"]
